FROM scratch

COPY a.txt /

# =============== check image size ===============
# docker image inspect f9d3 --format='{{.Size}}'

# =============== saving images to a tar archive ===============
# docker save -o ci.tar custom_image