version: '3.3'
services:
  fluentd:
    container_name: fluentd_container
    user: root
    image: fluentd
    volumes:
      - ./config:/fluentd/etc
      - ./logs:/output
  logger_app1:
    container_name: logger_app1_container
    image: alpine
    depends_on:
      - fluentd
    volumes:
      - ./http:/app
    command: [/bin/sh, -c, "apk add --no-cache curl && chmod +x /app/app.sh && ./app/app.sh AMMAR"]
  logger_app2:
      container_name: logger_app2_container
      image: alpine
      depends_on:
        - fluentd
      volumes:
        - ./http:/app
      command: [/bin/sh, -c, "apk add --no-cache curl && chmod +x /app/app.sh && ./app/app.sh SHEHERYAR"]